### PR TITLE
Added State System

### PR DESCRIPTION
**Pull request by gmanjames**
I added a general state system that can be used to create states for generic FlxObject. I extended the BaseState class that is at the core of this system to create a PlayerState class that can be extended to create player related states. Further, I extended this PlayerState class to create some basic player states that handle walking, running and jumping.

### CODE REVIEW

**Comment by gmanjames** [comment]
Sam, I am noticing some weird white space formatting things that are probably resulting from work on my machine. Might not want to merge this yet. Feel free to checkout branch and check everything out however

**Comment by SamBumgardner** [comment]
Gotcha. I'll either check it out late tonight or tomorrow morning.

**Comment by SamBumgardner** [comment]
Actually, I think you targeted the wrong branch with your PR? The basic-player branch has already been merged in, so your PR should target master, I think.

**Comment by gmanjames** [comment]
Ah ok, I should have pinged you. Wasn't sure which one you might want to merge it into first

**Comment by SamBumgardner** [comment]
Actually, I think the ideal situation is this:

You create a separate branch on your forked repository off of master, apply your commits to that, then submit a pull request from your own unique branch to the main repository's master branch.

We generally want to avoid situations like this one, where you worked further on your fork's version of a branch, then make a pull request back to the original version of that branch on the main repository. I'm not a big fan of having multiple branches with the same name that aren't really the same branch, and that's what's going on in this scenario.

**Pull request closed without merging**
